### ISSUE TITLE
Dialog focus does not return to button that initiated it on close

### ISSUE THREAD

**Issue by adplusverb** [thesmythgroup/vue-toolkit#22]
## Describe of the Issue

When the dialog/modal is closed focus goes to first element in page

## Expected behavior

Focus would return to "Open Dialog" button or whatever initiated the modal or had focus before it appeared

## Steps to Reproduce

Open a modal

Close a modal

Observe focus

## Other Information

n/a

**Comment by justinlettau** [comment]
Closed via 2242a2f
